name: CI_pytest_date2name

# name    : pytest.yml
# purpose : lightpytest (latest Python interpreter as available to GitHub)


on:
  push:
    branches:
      - master 
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:     # provide a manual trigger
  # schedule:
    # - cron: "0 0 1 * *"  # once each 1st of a month, at 00:00 UTC (cf. https://crontab.guru/)

# prevent concurrency of workflows (rule GH102):
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.x"]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 10  # Timeout for each job individually

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with PyPI
        run: | 
          pip install pytest
          pip install .

      - name: run the check by pytest
        run: |
          python -m pytest

